# Generated by Django 2.2.5 on 2019-10-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAula', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gafas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenador', models.CharField(max_length=2)),
                ('tipo', models.CharField(max_length=10)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubVR.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJuego', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('apellidoUsuario', models.CharField(max_length=200)),
                ('edadUsuario', models.CharField(max_length=100)),
                ('mailUsuario', models.CharField(max_length=100)),
                ('telefonoUsuario', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='date published')),
                ('fecha_fin', models.DateTimeField(verbose_name='date published')),
                ('id_gafas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubVR.Gafas')),
                ('id_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubVR.Juego')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubVR.Usuario')),
            ],
        ),
    ]
