# Generated by Django 2.2.5 on 2019-10-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubVR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefonoUsuario',
            field=models.IntegerField(verbose_name=999999999),
        ),
    ]
